getDir.o:getDir.c
	gcc -c  getDir.c  
getFile.o: getFile.c 
	gcc -c  getFile.c  
getFileType.o: getFileType.c
	gcc -c  getFileType.c  
moveDir.o: moveDir.c 
	gcc -c  moveDir.c  
moveFile: moveFile 
	gcc -c  moveFile.c  
removeDir.o: removeDir.c 
	gcc -c  removeDir.c  
removeFile.o: removeFile.c 
	gcc -c  removeFile.c  